### PR TITLE
v1.4.0

### PR DESCRIPTION
**Pull request by MatthewFlamm**

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
@lymanepp anything else you want to have in this release?

**Comment by lymanepp** [comment]
> @lymanepp anything else you want to have in this release?

Not that I can think of... I'm ready to start using the detailed forecast in a custom integration that I'm working on.

**Review by lymanepp — APPROVED** [review]
Looks good to me!

**Comment by MatthewFlamm** [comment]
> Not that I can think of... I'm ready to start using the detailed forecast in a custom integration that I'm working on.

This seems like a good candidate for including in the official integration as well.

**Comment by lymanepp** [comment]
The hourly forecast could be improved by using the detailed forecast.
* If the hourly forecast had relative humidity, I might be able to use the `nws` component's hourly `weather` entity instead of using `pynws` directly. Then my custom component would theoretically be able to work with other forecast providers.
* With relative humidity, we could add heat index attribute.
* Wind speed and bearing would be cleaner. Could add wind chill index attribute.
* I prefer [summer simmer index](http://summersimmer.com/home.htm) as my heat index. Could also add an SSI attribute.
* Could combine temperature, heat index and wind chill to create feels like temperature (also one for SSI).
* HA lacks standardized attributes for these forecast attributes. Is it feasible to extend that?

We could potentially augment daily forecasts, as well. But that would take a little more effort.

**Comment by MatthewFlamm** [comment]
The path forward for the official integration would be to assess whether the detailed forecast contains everything that the simple forecast does. 

If so, we can replace the hourly forecast with the detailed forecast data.  

If there is some different information missing in the detailed forecast, we make a decision to either make a breaking change or just provide a separate entity, like `weater.stn_detailed_hourly`

Anything not directly from NWS or some trivial extension is probably best as a custom integration.

**Comment by lymanepp** [comment]
These hourly forecast properties are not present in the grid data (detailed forecast). They are computed from the grid data by the NWS forecast API. The `isDaytime` property might be easy enough to compute. While we could attempt to reverse engineer the `icon` and `shortForecast` logic, I wouldn't recommend it.
```
"isDaytime": true,
"icon": "https://api.weather.gov/icons/land/day/few?size=small",
"shortForecast": "Sunny",
```

These hourly forecast properties are currently empty, but they could have a value someday.
```
"temperatureTrend": null,
"detailedForecast": ""
```

**Comment by MatthewFlamm** [comment]
From a homeassistant perspective, we would mostly need to make sure that there would be no breaking change.  As long as we can determine the forecast condition from the detailed forecast, then there is no breaking change.  I would think the icon and shortForecast are derived from the `"weather"` value(s).  We'd have to see if there is good documentation on the possible values like there was/is for the icon/shortForecast.

**Comment by lymanepp** [comment]
Now that pynws has support for detailed forecasts, my primary interest has shifted to creating my custom integration that requires hourly comfort information. I will use pynws directly at this point, but I will take another look in the future if the nws weather component ever makes the hourly humidity forecast available.

Until HA is updated to reference pynws 1.4.1+, I'm going to include a local copy in my custom integration.

BTW, thanks for integrating my changes!

**Comment by lymanepp** [comment]
> I would think the icon and shortForecast are derived from the `"weather"` value(s).

You're right that `weather` along with `skyCover`, `probabilityOfPrecipitation` and some other values are probably used to create the icon and shortForecast values. It would be awesome if they open-sourced their code.

> We'd have to see if there is good documentation on the possible values like there was/is for the icon/shortForecast.

* While it's only part of what is needed, the NWS API has a (deprecated) endpoint to [retrieve a list of condition abbreviations](https://api.weather.gov/icons).
* The sky conditions are from METAR and there is [some documentation](https://www.cfinotebook.net/notebook/weather-and-atmosphere/aviation-routine-weather-report#sky-condition) that would help in computing the icons.
* ~~HA already uses [astral](https://github.com/sffjunkie/astral) for the `sun` component. We could use that to calculate day/night that is needed for `isDaytime` and `icon`.~~ Edit: it looks like NWS just uses 6am to 6pm as day and the rest is night. The icons would be more accurate using astral, but not needed for compatibility.

I would like to stay active in the `pynws` module and I'd help with the above if you decide to move ahead with that.

**Comment by lymanepp** [comment]
Here's a little test I threw together to emulate NWS icon URLs. It works pretty well for all of the weather conditions that I've found so far. The NWS URLs are inconsistent regarding how many hours they should include precip probability--I include it for 12 hours and that created the fewest differences.

Edit: I updated the test program to generate short forecasts. Funky rules!

```
import asyncio
from datetime import datetime, timezone
from typing import Any

import aiohttp
import pytz

from pynws import SimpleNWS
from pynws.const import Detail
from pynws.raw_data import raw_points_stations

CITY_COORDS = {
    "Appleton, WI": (44.287, -88.467),
    "Denver, CO": (39.764, -104.995),
    "Dushore, PA": (41.524, -76.405),
    "Gainesville, FL": (29.686, -82.389),
    "Harrisburg, PA": (40.282, -76.915),
    "New York, NY": (40.697, -74.119),
    "Omaha, NE": (41.292, -96.221),
    "Portland, OR": (45.542, -122.794),
    "Red Lodge, MT": (45.193, -109.267),
    "Tabor City, NC": (34.158, -78.890),
    "Uvalde, TX": (29.212, -99.792),
    "Washington, DC": (38.893, -77.084),
}

USERID = "testing@address.xyz"


CONDITION_REPLACEMENTS = {
    "rain_showers_and_snow_showers": "rain_and_snow_showers",
    "rain_showers_and_thunderstorms": "showers_and_thunderstorms",
}

COVERAGE_REPLACEMENTS = {
    "numerous": "chance",
}

CONDITION_INTENSITIES = {
    "rain": ("light", "heavy"),
}

COVERAGE_PREFIXES = ("chance", "slight_chance", "isolated")
COVERAGE_SUFFIXES = ("likely",)


async def nws_icon_emulation():
    async with aiohttp.ClientSession() as session:
        for city, coord in CITY_COORDS.items():
            nws = SimpleNWS(*coord, USERID, session)
            await nws.set_station()
            await nws.update_forecast_hourly()
            await nws.update_detailed_forecast()

            raw_stations = await raw_points_stations(*coord, nws.session, USERID)
            tz_name = raw_stations["features"][0]["properties"][
                "timeZone"
            ]  # is there a better way?
            local_tz = pytz.timezone(tz_name)

            start_time = datetime.now(tz=timezone.utc).astimezone()
            detailed_forecast = list(
                nws.detailed_forecast.get_details_by_hour(
                    start_time, hours=len(nws.forecast_hourly)
                )
            )

            index = 0
            for hourly, detailed in zip(nws.forecast_hourly, detailed_forecast):
                index += 1

                start_time = datetime.fromisoformat(
                    detailed[Detail.START_TIME]
                ).astimezone(local_tz)
                daytime = 6 <= start_time.hour < 18

                detailed["isDaytime"] = daytime
                detailed["icon"] = create_icon_url(detailed, show_pop=index < 12)
                detailed["shortForecast"] = create_short_forecast(detailed)

                if detailed.get("icon") != hourly.get("icon"):
                    print(f" NWS URL: {hourly['icon']}")
                    print(f"Calc URL: {detailed['icon']}")
                    print()

                if hourly.get("shortForecast") != detailed.get("shortForecast"):
                    print(f" NWS forecast: {hourly['shortForecast']}")
                    print(f"Calc forecast: {detailed['shortForecast']}")
                    print()


def create_short_forecast(detailed: dict[Detail, Any]) -> str:
    if (short_forecast := create_forecast_from_weather(detailed)) is None:
        short_forecast = create_forecast_from_sky_cover(detailed)

    return short_forecast.replace("_", " ").title()


def create_forecast_from_weather(detailed: dict[Detail, Any]) -> str | None:
    conditions: list[str] = []
    intensities: list[str] = []
    coverages: list[str] = []

    for weather in detailed[Detail.WEATHER]:
        if condition := weather.get("weather"):
            conditions.append(condition)
            intensities.append(weather.get("intensity"))
            coverages.append(weather.get("coverage"))

    if not conditions:
        return None

    if len(conditions) == 1:
        condition, intensity, coverage = conditions[0], intensities[0], coverages[0]
        if intensity_list := CONDITION_INTENSITIES.get(condition, []):
            if intensity in intensity_list:
                condition = f"{intensity} {condition}"
    else:
        conditions.sort()
        condition = "_and_".join(conditions)
        coverage = coverages[0]

    condition = CONDITION_REPLACEMENTS.get(condition, condition)
    coverage = COVERAGE_REPLACEMENTS.get(coverage, coverage)

    if coverage in COVERAGE_PREFIXES:
        return f"{coverage} {condition}"
    if coverage in COVERAGE_SUFFIXES:
        return f"{condition} {coverage}"
    return condition


def create_forecast_from_sky_cover(detailed) -> str:
    sky_cover = detailed[Detail.SKY_COVER]
    if detailed.get("isDaytime"):
        if sky_cover <= 25:
            return "sunny"
        if sky_cover <= 50:
            return "mostly_sunny"
        if sky_cover <= 69:
            return "partly_sunny"
    else:
        if sky_cover <= 5:
            return "clear"
        if sky_cover <= 25:
            return "mostly_clear"
        if sky_cover <= 50:
            return "partly_cloudy"

    if sky_cover <= 86:
        return "mostly_cloudy"
    else:
        return "cloudy"


def create_icon_url(detailed: dict[Detail, Any], show_pop: bool):
    day_night = "day" if detailed.get("isDaytime") else "night"

    condition = None
    sky_cover = detailed[Detail.SKY_COVER]

    # sorting alphabetically is silly, but there is a priority order for the weather item to use
    for weather in sorted(
        detailed[Detail.WEATHER], key=lambda x: x.get("weather"), reverse=True
    ):
        if condition := weather.get("weather"):
            if condition == "thunderstorms":
                if sky_cover < 60:
                    condition = "tsra_hi"
                elif sky_cover < 75:
                    condition = "tsra_sct"
                else:
                    condition = "tsra"

            elif condition == "snow_showers":
                condition = "snow"

            if show_pop:
                if pop_rounded := round(detailed[Detail.PROBABILITY_OF_PRECIPITATION] / 10) * 10:
                    condition += f",{pop_rounded}"
        break

    if not condition:
        if sky_cover <= 5:
            condition = "skc"
        elif sky_cover <= 25:
            condition = "few"
        elif sky_cover <= 50:
            condition = "sct"
        elif sky_cover < 88:
            condition = "bkn"
        else:
            condition = "ovc"

        if detailed[Detail.WIND_SPEED] > 32:  # 32 km/h ≈ 20 mph
            condition = "wind_" + condition

    return f"https://api.weather.gov/icons/land/{day_night}/{condition}?size=small"


loop = asyncio.get_event_loop_policy().get_event_loop()
loop.run_until_complete(nws_icon_emulation())
```

**Pull request merged**
