### PR TITLE
Fix null value in qv for forecast

### LINKED ISSUE #131: null value in the new quantitative values in the forecast do not pass through correctly
https://github.com/home-assistant/core/issues/98135

### PR DESCRIPTION
**Pull request by MatthewFlamm**
closes #131

### CODE REVIEW

**Comment by MatthewFlamm** [comment]
The `extract_value` method was originally developed for the observations where it made things _slightly_ simpler to return a simple `None` when there was no value.  That is, it was easier to filter that value out when combining multiple incomplete observations together.

Now that it is also being used for forecasts, it is now making things more complicated.  This PR is a regression fix, but this method should be cleaned up to always return a tuple in the future.

**Comment by MatthewFlamm** [comment]
@lymanepp if you are able to review

**Review by lymanepp — APPROVED** [review]
LGTM

**Comment by MatthewFlamm** [comment]
I'm fairly certain that NWS uses `null` to mean 0% chance. Do you think we should make that change here?  I think it would be easier to use, but with the potential to sometimes give 0% when NWS actually meant to say unknown.

Edit: Thinking about this more, I think this is the best solution given the oddness of the NWS data here.

**Comment by lymanepp** [comment]
I'm fine with that if you're confident that null means zero. It would be an unfortunate API design if null also means unknown.

**Comment by MatthewFlamm** [comment]
The current forecast for my location is illuminating.  For forecasts with a stated % in the detailed forecast, it shows up as the same value in the `probabilityOfPrecipitation` key.  For forecasts like `Sunny ....`, the value in `probabilityOfPrecipitation` is `null`.  For forecasts like `Sunny with a slight chance of showers` it is still `null`, presumably because the chance is below some threshold.

**Review by lymanepp — APPROVED** [review]
Looks okay to me

**Pull request merged**
